---
title: "Impressum"
---

Information required under German Law (§ 5 DDG and § 55 RStV):

## Contact Information

Simon Nolte  
German Sport University Cologne  
Institute of Exercise Training and Sport Informatics  
Am Sportpark Müngersdorf 6  
50933 Cologne, Germany  

Email: [s.nolte@dshs-koeln.de](mailto:s.nolte@dshs-koeln.de)

## Disclaimer

### Accountability for Content

The contents of our pages have been created with the utmost care. However, we cannot guarantee the contents' accuracy, completeness, or topicality. According to statutory provisions, we are furthermore responsible for our own content on these web pages. In this context, please note that we are not obliged to monitor the transmitted or saved information of third parties or investigate circumstances pointing to illegal activity.

### Accountability for Links

Responsibility for the content of external links (to web pages of third parties) lies solely with the operators of the linked pages. No violations were evident to us at the time of linking. Should any legal infringement become known to us, we will remove the respective link immediately.
